name: dieklingel-core
title: dieKlingel Core
contact: kai.mayer@dieklingel.com
website: https://dieklingel.de/
license: GPL-3.0
version: 0.1.3+1
summary: The core of the dieKlingel project.
description: The core project containing the most important services to run the door unit.
confinement: strict
compression: lzo
base: core22
grade: stable

architectures:
#  - build-on: amd64
  - build-on: arm64

apps:
  dieklingel-core:
    daemon: simple
    restart-delay: 3s
    restart-condition: always
    command: bin/core
    plugs:
      - network
      - camera
      - audio-playback
      - audio-record 
      - pulseaudio
      - alsa
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/local/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/
      DIEKLINGEL_HOME: "$SNAP_USER_COMMON"
      GST_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0:$SNAP/usr/local/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0
      GST_PLUGIN_SCANNER: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner 

parts:
  dieklingel-core:
    plugin: go
    source: .
    build-snaps:
      - go
    override-build: |
      export LDFLAGS="-Wl,--copy-dt-needed-entries"
      snapcraftctl build
    build-packages:
      - libglib2.0-dev
      - pkg-config
      - libgtk-3-0
      - libgtk-3-dev # libgio-2.0.a(giomodule.c.o): undefined reference to symbol 'g_module_open_full'
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
    stage-packages:
      - libdw-dev
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer-plugins-bad1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - gstreamer1.0-tools
      - gstreamer1.0-x
      - gstreamer1.0-alsa
      - gstreamer1.0-gl
      - gstreamer1.0-gtk3
      - gstreamer1.0-qt5
      - gstreamer1.0-pulseaudio
      
  libcamera:
    plugin: meson
    source: https://github.com/raspberrypi/libcamera.git
    build-packages:
      - libsnapd-glib-dev
      - libglib2.0-dev
      - libffi-dev
      - clang
      - meson
      - ninja-build
      - pkg-config
      - libyaml-dev
      - python3-yaml
      - python3-ply
      - python3-jinja2
      - libgnutls28-dev
      - libudev-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev