name: "Run Tests and Build for Linux"
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  snapcraft-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build snapcraft
        uses: snapcore/action-build@v1
