name: Create a tag, with the name of the current version, specified in snapcraft.yaml
on:
  push:
    branches:
      - main
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get current version
        run: |
            VERSION_TAG=v$(cat snap/snapcraft.yaml | grep -Po '(?<=version:\s)(.*)')
            echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
      - uses: mukunku/tag-exists-action@v1.0.0
        id: tag
        with: 
          tag: ${{ env.VERSION_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: compare tags
        run: |
            if [ "${{ steps.tag.outputs.exists }}" == "true" ]; then
              echo "tag already exists, no need to create a new release"
              exit 0
            fi
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.VERSION_TAG }}
          message: "tag created: ${{ env.VERSION_TAG }}"
